### ISSUE TITLE
Edição de endereço está mudando o campo addressName

### ISSUE THREAD

**Issue by klzns** [vtex-apps/my-account#37]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

**Comment by akaFTS** [comment]
The code responsible for this bug is located inside the `AddressFormBox` component. 

:)
