### ISSUE TITLE
Exibir o codigo de rastreio na pagina area de acompanhamento do pedido 

### ISSUE THREAD

**Issue by fabiobarbosavtex** [vtex-apps/my-account#51]
Hoje o My Account nao exibe o código de rastreio que é inserido no pedido, o cliente Foreverliss ,solicitou que se possivel o codigo fosse exibido, pois em alguns casos a transportadora pode nao ter integraçao ou a integraçao nao esteja funcionando o cliente ao menos teria como acessar o código.

Variavel "trackingNumber" orderform

**Comment by salesfelipe** [comment]
Moved to clubhouse
