### ISSUE TITLE
Help with My Account:  Retrieving Information from Masterdata. 

### ISSUE THREAD

**Issue by juliaguerino01** [vtex-apps/my-account#70]
**Describe the bug**
Hi everyone, I'm having some problems retrieving information from 
my customers when I try to display their address and also I just can't
add any new address. The button doesn't work. 
I checked the Masterdata and everything looks fine. However, if I inspect the page, 
Google Chrome shows me the following error: 

"Failed to load resource: the server responded with a status of 400 ()"

**Expected behavior**
If I have an account, I need to display my information (in this case my address/addresses or when I click the "Add Adress" button I want to be able to add more information! We never know what the customer wants us to know about them!

**Screenshots**
Screenshots of the errors:

https://drive.google.com/file/d/10u0OTnX_QClb7_GLiP9X2Fg3Z7HckD8o/view?usp=sharing
https://drive.google.com/file/d/1jAgRBp9oGk-OfMRlnTcHs4OeZbfqy1zl/view?usp=sharing

**Desktop (please complete the following information):**

- OS: Windows, MAC. 
- Browser: Chrome. 
- Version: Last version (March/2019)

**Additional context**
Thanks in advance.

**Comment by salesfelipe** [comment]
Your prints are unavailable
