### ISSUE TITLE
CSS to CreditCard

### ISSUE THREAD

**Issue by fpsman** [vtex-apps/my-account#90]
**Describe the bug**
We can't add CSS rules to "Cards" section, because it is loaded inside an iframe and the iframe doesn't load any custom CSS.

**Expected behavior**
The iframe has a custom CSS call to add style.

**Comment by fpsman** [comment]
![image](https://user-images.githubusercontent.com/1374326/59726900-e2445200-9209-11e9-8c67-856f36cefa52.png)

**Comment by kaisermann** [comment]
Resolved! All stylesheets loaded as `<link rel="stylesheet" href="..."/>` from the main website will be also loaded inside the form's `iframe`.

**Comment by fpsman** [comment]
Nice, validated! Thanks!

**Comment by kaisermann** [comment]
Hey @Rassaster and @javierenciso 👋  I don't work at VTEX anymore, so I wouldn't know, sorry! 😁 🤷

**Comment by AngelBS** [comment]
Same problem here, any update about this issue? on my workspace the buttons appear with transparent background and i'm unable to change the color unless i use :global() but it impacts the whole site
